/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import Controller.DAO;
import Controller.DAOBooks;
import Controller.DataValidator;
import Controller.MessageDialogHelper;
import Model.Books;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VietNguyen
 */
public class BookManagementPanel extends javax.swing.JPanel {

    private formAdmin formAdmin;
    
    public BookManagementPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jB_bookSearch = new javax.swing.JLabel();
        txt_bookSearch = new javax.swing.JTextField();
        btn_bookSearch = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jB_maSach = new javax.swing.JLabel();
        txt_MaSach = new javax.swing.JTextField();
        jB_BookName = new javax.swing.JLabel();
        txt_BookName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_TheLoai = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btn_addBooks = new javax.swing.JButton();
        btn_EditBooks = new javax.swing.JButton();
        btn_removeBooks = new javax.swing.JButton();
        btn_New = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBooks = new javax.swing.JTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jB_bookSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jB_bookSearch.setText("Mã Sách: ");

        txt_bookSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_bookSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_bookSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/search-icon.png"))); // NOI18N
        btn_bookSearch.setText("Tìm Kiếm");
        btn_bookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jB_bookSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_bookSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_bookSearch))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_bookSearch)
                    .addComponent(txt_bookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bookSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Thông Tin Sách:");

        jB_maSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jB_maSach.setText("Mã Sách: ");

        txt_MaSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jB_BookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jB_BookName.setText("Tên Sách: ");

        txt_BookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Thể Loại: ");

        txt_TheLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jB_maSach)
                        .addGap(18, 18, 18)
                        .addComponent(txt_MaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jB_BookName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_BookName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TheLoai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_maSach)
                    .addComponent(txt_MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_BookName)
                    .addComponent(txt_BookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btn_addBooks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_addBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/Add-icon-18.png"))); // NOI18N
        btn_addBooks.setText("Thêm Sách");
        btn_addBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addBooksActionPerformed(evt);
            }
        });

        btn_EditBooks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_EditBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/Actions-document-edit-icon.png"))); // NOI18N
        btn_EditBooks.setText("Sửa ");
        btn_EditBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditBooksActionPerformed(evt);
            }
        });

        btn_removeBooks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_removeBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinhNen/Icon/Actions-window-close-icon.png"))); // NOI18N
        btn_removeBooks.setText("Xóa Sách");
        btn_removeBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeBooksActionPerformed(evt);
            }
        });

        btn_New.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_New.setText("Làm Mới");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_removeBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_EditBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addBooks)
                    .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_addBooks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btn_EditBooks)
                .addGap(18, 18, 18)
                .addComponent(btn_removeBooks)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Chi Tiết Sách: ");

        tableBooks.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Thể Loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBooks.getTableHeader().setReorderingAllowed(false);
        tableBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBooks);
        if (tableBooks.getColumnModel().getColumnCount() > 0) {
            tableBooks.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableBooks.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void showData(){
        try {
            tableBooks.removeAll();
            String[] arr = {"Mã Sách", "Tên Sách", "Thể Loại"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);
            Connection connection = DAO.getConnection();
            String querry = "SELECT * FROM dbo.[SACH] ORDER BY tenSach";
            PreparedStatement ps = connection.prepareStatement(querry);
            ps.executeQuery();
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("MaSach"));
                vector.add(rs.getString("TenSach"));
                vector.add(rs.getString("TheLoai"));
                model.addRow(vector);
            }
            tableBooks.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(BookManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }     
 
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        showData();
    }//GEN-LAST:event_formComponentShown

    private void btn_bookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookSearchActionPerformed
        try {
            String id = (String) txt_bookSearch.getText();
            DAOBooks dao = new DAOBooks();
            Books sach = dao.timSach(id);
            if(sach != null){
                txt_MaSach.setText(sach.getMaSach());
                txt_BookName.setText(sach.getTenSach());
                txt_TheLoai.setText(sach.getTheLoai());
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(formAdmin,"Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_btn_bookSearchActionPerformed

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        txt_BookName.setText("");
        txt_MaSach.setText("");
        txt_TheLoai.setText("");
    }//GEN-LAST:event_btn_NewActionPerformed

    private void btn_addBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addBooksActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txt_MaSach, sb, "Mã Sách không được để trống");
        if (sb.length()>0) {
            MessageDialogHelper.showErrorDialog(formAdmin, sb.toString(), "Lỗi");
        }
        try {
            Books sach = new Books();
            sach.setMaSach(txt_MaSach.getText());
            sach.setTenSach(txt_BookName.getText());
            sach.setTheLoai(txt_TheLoai.getText());
            
            DAOBooks dao = new  DAOBooks();
            if(dao.themSach(sach)){
                MessageDialogHelper.showMessageDialog(formAdmin, "Thông Báo", "Thêm Sách thành công");
            }else{
                MessageDialogHelper.showConfirmDialog(formAdmin, "Cảnh Báo", "Thêm Sách Thất Bại");
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(formAdmin, e.getMessage(), "Lỗi");
        }
        showData();
    }//GEN-LAST:event_btn_addBooksActionPerformed

    private void btn_EditBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditBooksActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txt_MaSach, sb, "Mã Sách không được để trống");
        if (sb.length()>0) {
            MessageDialogHelper.showErrorDialog(formAdmin, "Lỗi", sb.toString());
        }else if (MessageDialogHelper.showConfirmDialog(formAdmin, "Hỏi", "Bạn có muốn cập nhật thông tin ?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            Books sach = new Books();
            sach.setMaSach(txt_MaSach.getText());
            sach.setTenSach(txt_BookName.getText());
            sach.setTheLoai(txt_TheLoai.getText());
            
            DAOBooks dao = new  DAOBooks();
            if(dao.suaSach(sach)){
                MessageDialogHelper.showMessageDialog(formAdmin, "Thông Báo", "Sửa Thông Tin Sách thành công");
            }else{
                MessageDialogHelper.showConfirmDialog(formAdmin, "Cảnh Báo", "Sửa Thông Tin Sách Thất Bại");
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(formAdmin,"Lỗi", e.getMessage());
        }
        showData();
    }//GEN-LAST:event_btn_EditBooksActionPerformed

    private void btn_removeBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeBooksActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txt_MaSach, sb, "Mã Sách không được để trống");
        if (sb.length()>0) {
            MessageDialogHelper.showErrorDialog(formAdmin, "Lỗi", sb.toString());
        }else if (MessageDialogHelper.showConfirmDialog(formAdmin, "Hỏi", "Bạn có muốn xóa sách ?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            DAOBooks dao = new DAOBooks();
            if(dao.xoaSach(txt_MaSach.getText())){
                MessageDialogHelper.showMessageDialog(formAdmin, "Thông Báo", "Xóa Sách thành công");
                btn_NewActionPerformed(evt);
            }else{
                MessageDialogHelper.showConfirmDialog(formAdmin, "Cảnh Báo", "Xóa Thông Tin Sách Thất Bại");
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(formAdmin,"Lỗi", e.getMessage());
        }
        showData();
    }//GEN-LAST:event_btn_removeBooksActionPerformed

    private void tableBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBooksMouseClicked
        try {
            int row = tableBooks.getSelectedRow();
            if (row >= 0){
                String id = (String) tableBooks.getValueAt(row, 0);
                DAOBooks dao = new DAOBooks();
                Books sach = dao.timSach(id);
                if(sach != null){
                    txt_MaSach.setText(sach.getMaSach());
                    txt_BookName.setText(sach.getTenSach());
                    txt_TheLoai.setText(sach.getTheLoai());
                }
            }
        } catch (Exception e) {
            MessageDialogHelper.showErrorDialog(formAdmin,"Lỗi", e.getMessage());
        }
    }//GEN-LAST:event_tableBooksMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EditBooks;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_addBooks;
    private javax.swing.JButton btn_bookSearch;
    private javax.swing.JButton btn_removeBooks;
    private javax.swing.JLabel jB_BookName;
    private javax.swing.JLabel jB_bookSearch;
    private javax.swing.JLabel jB_maSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableBooks;
    private javax.swing.JTextField txt_BookName;
    private javax.swing.JTextField txt_MaSach;
    private javax.swing.JTextField txt_TheLoai;
    private javax.swing.JTextField txt_bookSearch;
    // End of variables declaration//GEN-END:variables
}
